{
 "PRed": [
  {
   "PR": {
    "__lazy_json__": "pr_json/502018641.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "0.1.1"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/597439463.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "0.1.2"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/700658114.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "0.1.3"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  }
 ],
 "archived": false,
 "bad": false,
 "branch": "master",
 "conda-forge.yml": {},
 "feedstock_name": "pytest-github-actions-annotate-failures",
 "hash_type": "sha256",
 "linux_64_meta_yaml": {
  "about": {
   "home": "https://github.com/utgwkk/pytest-github-actions-annotate-failures",
   "license": "MIT",
   "license_file": "LICENSE",
   "summary": "pytest plugin to annotate failed tests with a workflow command for GitHub Actions"
  },
  "build": {
   "noarch": "python",
   "number": "0",
   "script": "/usr/share/miniconda/envs/run_env/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python -m pip install . -vv"
  },
  "extra": {
   "recipe-maintainers": [
    "bollwyvl"
   ]
  },
  "package": {
   "name": "pytest-github-actions-annotate-failures",
   "version": "0.1.2"
  },
  "requirements": {
   "host": [
    "pip",
    "python ==2.7|>=3.6"
   ],
   "run": [
    "pytest >=4.0.0",
    "python ==2.7|>=3.6"
   ]
  },
  "source": {
   "sha256": "9eb6ee2943ecde2078fe620af7dbf32646c0267f538435cd805fe2e8d735ca3a",
   "url": "https://pypi.io/packages/source/p/pytest-github-actions-annotate-failures/pytest-github-actions-annotate-failures-0.1.2.tar.gz"
  },
  "test": {
   "commands": [
    "python -m pip check"
   ],
   "imports": [
    "pytest_github_actions_annotate_failures"
   ],
   "requires": [
    "pip"
   ]
  }
 },
 "linux_64_requirements": {
  "build": {
   "__set__": true,
   "elements": []
  },
  "host": {
   "__set__": true,
   "elements": [
    "pip",
    "python"
   ]
  },
  "run": {
   "__set__": true,
   "elements": [
    "pytest",
    "python"
   ]
  },
  "test": {
   "__set__": true,
   "elements": [
    "pip"
   ]
  }
 },
 "meta_yaml": {
  "about": {
   "home": "https://github.com/utgwkk/pytest-github-actions-annotate-failures",
   "license": "MIT",
   "license_file": "LICENSE",
   "summary": "pytest plugin to annotate failed tests with a workflow command for GitHub Actions"
  },
  "build": {
   "noarch": "python",
   "number": "0",
   "script": "/usr/share/miniconda/envs/run_env/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python -m pip install . -vv"
  },
  "extra": {
   "recipe-maintainers": [
    "bollwyvl"
   ]
  },
  "package": {
   "name": "pytest-github-actions-annotate-failures",
   "version": "0.1.2"
  },
  "requirements": {
   "host": [
    "pip",
    "python ==2.7|>=3.6"
   ],
   "run": [
    "pytest >=4.0.0",
    "python ==2.7|>=3.6"
   ]
  },
  "source": {
   "sha256": "9eb6ee2943ecde2078fe620af7dbf32646c0267f538435cd805fe2e8d735ca3a",
   "url": "https://pypi.io/packages/source/p/pytest-github-actions-annotate-failures/pytest-github-actions-annotate-failures-0.1.2.tar.gz"
  },
  "test": {
   "commands": [
    "python -m pip check"
   ],
   "imports": [
    "pytest_github_actions_annotate_failures"
   ],
   "requires": [
    "pip"
   ]
  }
 },
 "name": "pytest-github-actions-annotate-failures",
 "new_version": "0.1.3",
 "new_version_attempts": {
  "0.1.1": 1,
  "0.1.2": 1,
  "0.1.3": 1
 },
 "new_version_errors": {},
 "outputs_names": {
  "__set__": true,
  "elements": [
   "pytest-github-actions-annotate-failures"
  ]
 },
 "pinning_version": "2021.07.30.11.17.02",
 "raw_meta_yaml": "{% set name = \"pytest-github-actions-annotate-failures\" %}\n{% set version = \"0.1.2\" %}\n\n# TODO:\n# - version >0.1.0 (unreleased) includes LICENSE in sdist, remove from feedstock\n\npackage:\n  name: {{ name|lower }}\n  version: {{ version }}\n\nsource:\n  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-github-actions-annotate-failures-{{ version }}.tar.gz\n  sha256: 9eb6ee2943ecde2078fe620af7dbf32646c0267f538435cd805fe2e8d735ca3a\n\nbuild:\n  number: 0\n  noarch: python\n  script: {{ PYTHON }} -m pip install . -vv\n\nrequirements:\n  host:\n    - pip\n    - python ==2.7|>=3.6\n  run:\n    - pytest >=4.0.0\n    - python ==2.7|>=3.6\n\ntest:\n  imports:\n    - pytest_github_actions_annotate_failures\n  commands:\n    - python -m pip check\n  requires:\n    - pip\n\nabout:\n  home: https://github.com/utgwkk/pytest-github-actions-annotate-failures\n  summary: pytest plugin to annotate failed tests with a workflow command for GitHub Actions\n  license: MIT\n  license_file: LICENSE\n\nextra:\n  recipe-maintainers:\n    - bollwyvl\n",
 "req": {
  "__set__": true,
  "elements": [
   "pip",
   "pytest",
   "python"
  ]
 },
 "requirements": {
  "build": {
   "__set__": true,
   "elements": []
  },
  "host": {
   "__set__": true,
   "elements": [
    "pip",
    "python"
   ]
  },
  "run": {
   "__set__": true,
   "elements": [
    "pytest",
    "python"
   ]
  },
  "test": {
   "__set__": true,
   "elements": [
    "pip"
   ]
  }
 },
 "smithy_version": "3.11.0",
 "strong_exports": false,
 "total_requirements": {
  "build": {
   "__set__": true,
   "elements": []
  },
  "host": {
   "__set__": true,
   "elements": [
    "pip",
    "python ==2.7|>=3.6"
   ]
  },
  "run": {
   "__set__": true,
   "elements": [
    "pytest >=4.0.0",
    "python ==2.7|>=3.6"
   ]
  },
  "test": {
   "__set__": true,
   "elements": [
    "pip"
   ]
  }
 },
 "url": "https://pypi.io/packages/source/p/pytest-github-actions-annotate-failures/pytest-github-actions-annotate-failures-0.1.2.tar.gz",
 "version": "0.1.2"
}