{
  "done": [
    "pytorch_cluster",
    "torchvision",
    "norse",
    "fairscale"
  ],
  "in-pr": [
    "pytorch_scatter",
    "pytorch_spline_conv",
    "torchsparse",
    "fcos"
  ],
  "awaiting-pr": [],
  "not-solvable": [
    "nvidia-apex"
  ],
  "awaiting-parents": [],
  "bot-error": [
    "torch-scatter",
    "torchani"
  ],
  "_feedstock_status": {
    "torchvision": {
      "num_descendants": 3,
      "immediate_children": [
        "fairscale",
        "fcos",
        "norse"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/torchvision-feedstock/pull/36",
      "pr_status": "clean"
    },
    "nvidia-apex": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1765091880\">bot CI job</a>): master: ['win_64_cuda_compiler_version10.2python3.7.____cpython: Encountered problems while solving:\\n  - nothing provides requested pytorch 1.10.*\\n', 'win_64_cuda_compiler_version10.2python3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested pytorch 1.10.*\\n', 'win_64_cuda_compiler_version10.2python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pytorch 1.10.*\\n', 'win_64_cuda_compiler_version11.0python3.7.____cpython: Encountered problems while solving:\\n  - nothing provides requested pytorch 1.10.*\\n', 'win_64_cuda_compiler_version11.0python3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested pytorch 1.10.*\\n', 'win_64_cuda_compiler_version11.0python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pytorch 1.10.*\\n', 'win_64_cuda_compiler_version11.1python3.7.____cpython: Encountered problems while solving:\\n  - nothing provides requested pytorch 1.10.*\\n', 'win_64_cuda_compiler_version11.1python3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested pytorch 1.10.*\\n', 'win_64_cuda_compiler_version11.1python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pytorch 1.10.*\\n', 'win_64_cuda_compiler_version11.2python3.7.____cpython: Encountered problems while solving:\\n  - nothing provides requested pytorch 1.10.*\\n', 'win_64_cuda_compiler_version11.2python3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested pytorch 1.10.*\\n', 'win_64_cuda_compiler_version11.2python3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pytorch 1.10.*\\n', 'win_64_cuda_compiler_versionNonepython3.7.____cpython: Encountered problems while solving:\\n  - nothing provides requested pytorch 1.10.*\\n', 'win_64_cuda_compiler_versionNonepython3.8.____cpython: Encountered problems while solving:\\n  - nothing provides requested pytorch 1.10.*\\n', 'win_64_cuda_compiler_versionNonepython3.9.____cpython: Encountered problems while solving:\\n  - nothing provides requested pytorch 1.10.*\\n']"
    },
    "pytorch_cluster": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/pytorch_cluster-feedstock",
      "pr_status": null
    },
    "pytorch_scatter": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/pytorch_scatter-feedstock/pull/36",
      "pr_status": "unstable"
    },
    "pytorch_spline_conv": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/pytorch_spline_conv-feedstock/pull/18",
      "pr_status": "unstable"
    },
    "torchani": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1765091880\">bot CI job</a>): master: Traceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 1133, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 269, in run\n    eval_cmd(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/utils.py\", line 271, in eval_cmd\n    c = subprocess.run(\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/subprocess.py\", line 507, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/subprocess.py\", line 1134, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/subprocess.py\", line 1980, in _communicate\n    self._check_timeout(endtime, orig_timeout, stdout, stderr)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/subprocess.py\", line 1178, in _check_timeout\n    raise TimeoutExpired(\nsubprocess.TimeoutExpired: Command 'conda smithy rerender -c auto --no-check-uptodate' timed out after 300 seconds\n"
    },
    "torchsparse": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/torchsparse-feedstock/pull/14",
      "pr_status": "clean"
    },
    "fcos": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/fcos-feedstock/pull/4",
      "pr_status": "clean"
    },
    "torch-scatter": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1765337910\">bot CI job</a>): master: Traceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 1133, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 269, in run\n    eval_cmd(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/utils.py\", line 271, in eval_cmd\n    c = subprocess.run(\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/subprocess.py\", line 507, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/subprocess.py\", line 1134, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/subprocess.py\", line 1980, in _communicate\n    self._check_timeout(endtime, orig_timeout, stdout, stderr)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/subprocess.py\", line 1178, in _check_timeout\n    raise TimeoutExpired(\nsubprocess.TimeoutExpired: Command 'conda smithy rerender -c auto --no-check-uptodate' timed out after 300 seconds\n"
    },
    "norse": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/norse-feedstock/pull/2",
      "pr_status": "unknown"
    },
    "fairscale": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/fairscale-feedstock",
      "pr_status": null
    }
  }
}